# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  interviewdotnetplayground:
    image: interviewdotnetplayground
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5015:5015
